int cut11()
{
printf("                            `.-----:shhmmdho: \n");                                                                                      
printf("                        `-/:::-----:+dhoyymmds:      \n");                                                                               
printf("                      :s+/:/:::::/+ydmdhdmmdmNmh:`          \n");                                                                        
printf("                    .ydo////:/+++++oshdNNNMMMMMMNNds+.             \n");                                                                 
printf("                   :dNh::-://+/:-/ohmNMMMMMMMMMMMNNNNNd+`                 \n");                                                          
printf("                  /dmmo//:::--/sdNMMMMMMMMMMMMMMMMNNNNNNm:                       \n");                                                   
printf("                 :dmmms+/++/odNNNNNNNNNNMMMMMMMMMMMMNNNNNm.                             \n");                                            
printf("                .hmmmmdssymNNNmddddddmmmmmmNNMMMMMMMMNNNNmo          -O QUE FAZ AQUI IRMAO, ESTA MUITO LONGE DE CASA!- Carol\n");                                                               
printf("               `ymmNmmmdhmNNdhyssssyyyyhhhhdmNMMMMMMMMMNNd-                                                                       \n");  
printf("               smNmmmNNmmNNdso++ssyssossyhhhdmNNMMMMMMNdo.           -ESTOU AQUI PARA VINGAR NOSSO PAI, SUAS ACOES CUSTARAM A VIDA DELE-Joao \n");                                                              
printf("              .mmmmNNNNNNmho+syyyhddmmmmmdhmdmNNNMMMNNN-                                                                          \n");  
printf("              -mNNNNNNNNNs+/+sydhmNNNNmdhyhNNNNNNNMMNNm              -SERIA MINHA CULPA, SE O PLANO DE TE TRAZER AQUI NAO FOSSE DELE- Carol\n");                                                               
printf("            :sdNmNNNmmmNh/:::/ooshddmdsoo+smmdNNNMMNMN/              -MAS JA QUE ESTA AQUI! SE ALIE AO MEU POVO!- Carol  \n");                                                             
printf("            yhdmmdhdddmh+//::::::/+ossoo+++hdddmmmMNNNy                                                                         \n");    
printf("            `smmmdhNhyyo+++//::::/+oyyyo///ohdmdmdNNNNN`                                                                          \n");  
printf("             -mmNdhhhysooooo++++++osyhhyyhhdmmmmmms:ydh                                                                           \n");  
printf("             `dNNmNdyyhyssssooooooosssssshdmmmmmNh`                                                                               \n");  
printf("              `--hNNNNNmhsssssssyyyyysssyydmmmNNN/                                                                                \n");  
printf("                 /mmNNNNmyyssyyyyyyhdhhhddmNNNNms                                                                                 \n");  
printf("                 .dmmNNNMyyyyyyhhhhhyyyhdmNNNmNy`                                                                                 \n");  
printf("                  odmNNMmssyhhhhhhyyyyyyhdmNNmo`                                                                                  \n");  
printf("               `-:/syhmNyossyhhdddhhhhhddmNNh-                                                                                    \n");  
printf("        -++ossossosssoshhyssyyhhhddmmmmmNms/`                                                                                     \n");  
printf("       .syo+osyo-:/osssyyddhhhhhdddmNNNNd.                                                                                        \n");  
printf("      `..-:::.-://++oshyyhdmmmmmmmmNNNNm.                                                                                         \n");  
printf("      /oo+--:+oo+/+syhhyyyyhddNMMNNNNNNm/                                                                                         \n");  
printf("     `s/--/+syhddmdddmmmmddmdyydNNNNNNNMmo`                                                                                       \n");  
printf("     /o/osyhddmmmNNNNNNNNNNNNmddmNNNNmMMNNd-``                                                                                    \n");  
printf("     oyyssyyydmmmmmmmNNNmmmmmmmdmNMNNNMMMNNmddy`                                                                                  \n");  
printf("     os//ooyhhdmmdmdmmNNMmhdmmmdmmmNNNNMMMNmNm+                                                                                   \n");  
printf("   `-oy/+oyhhddmmmmmmmmNNMNNNNmNMMMNNNNMMMMNNh-                                                                                   \n");  
printf("  :++s++ydyyydmmmmmmmmmmNNNNNNNNMMMMmMNNMMMMNNm/                                                                                  \n");  
printf(" /hyhyddhddmmmdmNNmmNNNNNNNmNNNNNMMMmNMNNMMMNNNmy+`                                                                               \n");  
printf("ohdyssdmNmmmmmNmmmNNNmmmmNNNNNNMMMMMMNmMNNMMMMNNNN-                                                                               \n");  
printf("mmshhNmmddmmmmmmNNNNNNmmmNNNNNNMMMMMMMMMMNMMMMMNNm                                                                                \n");  
printf("mhhdddmmmmmmNNmmNNmNNmNNmmNNNNNNNNMNMMMMMMMMNNMNNd                                                                                \n");  
printf("mhyhdmddmmmmmNNmNNNNNNNNNmmNMNNNNNNNNNMMMMMNNNMMNN:\n");  
}
